global using AssetManagement.Infrastructure.ConfigurationOptions;
global using AssetManagement.Infrastructure.Data;
global using AssetManagement.Infrastructure.Repositories;
global using AssetManagement.Infrastructure.Extensions;