name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pr:
  branches:
    include:
      - main

  paths:
    include:
      - 'AssetManagement/AssetManagement.Application/*'
      - 'AssetManagement/AssetManagement.Core/*'
      - 'AssetManagement/AssetManagement.Infrastructure/*'
      - 'AssetManagement/AssetManagement.Api/*'
      - './azure-pipelines/pr-pipeline.yml'

pool:
  name: Default
  demands:
    - Agent.Name -equals $(AGENT_NAME)

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  solution: 'AssetManagement/AssetManagement.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
stages:
  - stage: Build
    displayName: 'CI: Build'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: UseDotNet@2
            displayName: 'USe .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '9.x'

          - task: DotNetCoreCLI@2
            displayName: 'Restore NuGet Packages'
            inputs:
              command: 'restore'
              projects: '$(solution)'
              feedsToUse: 'select'
              
          - task: DotNetCoreCLI@2
            displayName: 'Build Solution'
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration $(buildConfiguration) --no-restore'
